#include "http.h"

#include <curl/curl.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>

#define AFM_USER_AGENT "anonfm_vsrat_reader/0.1"

/* Embedded Mozilla CA bundle (generated by CMake from vendor/cacert.pem). */
extern const unsigned char afm_cacert_data[];
extern const unsigned long afm_cacert_size;

struct afm_buf {
    char  *data;
    size_t len;
    size_t cap;
};

static size_t afm_write_cb(void *ptr, size_t size, size_t nmemb, void *user)
{
    struct afm_buf *b   = (struct afm_buf *)user;
    size_t          add = size * nmemb;
    size_t          need;
    char           *p;

    if (add == 0) return 0;
    need = b->len + add + 1;
    if (need > b->cap) {
        size_t new_cap = b->cap == 0 ? 8192 : b->cap;
        while (new_cap < need) new_cap *= 2;
        p = (char *)realloc(b->data, new_cap);
        if (p == NULL) return 0;
        b->data = p;
        b->cap  = new_cap;
    }
    memcpy(b->data + b->len, ptr, add);
    b->len += add;
    b->data[b->len] = '\0';
    return add;
}

int afm_http_global_init(void)
{
    return curl_global_init(CURL_GLOBAL_DEFAULT) == CURLE_OK ? 0 : -1;
}

void afm_http_global_cleanup(void)
{
    curl_global_cleanup();
}

int afm_http_get(const char *url, char **out_buf, size_t *out_len)
{
    CURL          *curl;
    CURLcode       rc;
    struct afm_buf b;
    long           http_code = 0;

    if (out_buf != NULL) *out_buf = NULL;
    if (out_len != NULL) *out_len = 0;
    if (url == NULL)     return -1;

    b.data = NULL;
    b.len  = 0;
    b.cap  = 0;

    curl = curl_easy_init();
    if (curl == NULL) return -1;

    curl_easy_setopt(curl, CURLOPT_URL,            url);
    curl_easy_setopt(curl, CURLOPT_USERAGENT,      AFM_USER_AGENT);
    curl_easy_setopt(curl, CURLOPT_FOLLOWLOCATION, 1L);
    curl_easy_setopt(curl, CURLOPT_TIMEOUT,        15L);
    curl_easy_setopt(curl, CURLOPT_CONNECTTIMEOUT, 8L);
    curl_easy_setopt(curl, CURLOPT_NOSIGNAL,       1L);
    curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION,  afm_write_cb);
    curl_easy_setopt(curl, CURLOPT_WRITEDATA,      &b);
    curl_easy_setopt(curl, CURLOPT_ACCEPT_ENCODING, "");
    {
        struct curl_blob ca_blob;
        ca_blob.data  = (void *)afm_cacert_data;
        ca_blob.len   = (size_t)afm_cacert_size;
        ca_blob.flags = CURL_BLOB_NOCOPY;
        curl_easy_setopt(curl, CURLOPT_CAINFO_BLOB, &ca_blob);
    }

    rc = curl_easy_perform(curl);
    if (rc == CURLE_OK) {
        curl_easy_getinfo(curl, CURLINFO_RESPONSE_CODE, &http_code);
    }
    curl_easy_cleanup(curl);

    if (rc != CURLE_OK) {
        fprintf(stderr, "http: %s\n", curl_easy_strerror(rc));
        free(b.data);
        return -1;
    }
    if (http_code < 200 || http_code >= 300) {
        fprintf(stderr, "http: status %ld\n", http_code);
        free(b.data);
        return -1;
    }

    if (out_buf != NULL) *out_buf = b.data;
    else                 free(b.data);
    if (out_len != NULL) *out_len = b.len;
    return 0;
}
